import { Theme } from './types';

export const transitThemes: Theme[] = [
  {
    id: 'berlin-dark',
    name: 'Berlin Dark',
    background: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 50%, #0a0a0a 100%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.8)',
    accentColor: '#4a90e2',
    style: 'minimal',
    clockStyle: 'digital',
    fontFamily: '"Inter", "Helvetica Neue", sans-serif',
    layout: 'split',
  },
  {
    id: 'berlin-gradient',
    name: 'Berlin Gradient',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.9)',
    accentColor: '#ffffff',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Inter", "Helvetica Neue", sans-serif',
    layout: 'split',
  },
  {
    id: 'tokyo-transit',
    name: 'Tokyo Transit',
    background: 'linear-gradient(135deg, #141e30 0%, #243b55 100%)',
    backgroundImage: 'radial-gradient(circle at 20% 50%, rgba(120,200,255,0.1) 0%, transparent 50%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.85)',
    accentColor: '#00d4ff',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Roboto", sans-serif',
    layout: 'split',
  },
  {
    id: 'london-underground',
    name: 'London Underground',
    background: 'linear-gradient(135deg, #000428 0%, #004e92 100%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.9)',
    accentColor: '#ff0000',
    style: 'minimal',
    clockStyle: 'digital',
    fontFamily: '"Johnston", "Arial", sans-serif',
    layout: 'split',
  },
  {
    id: 'stockholm-metro',
    name: 'Stockholm Metro',
    background: 'linear-gradient(135deg, #1e3c72 0%, #2a5298 50%, #7e57c2 100%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.85)',
    accentColor: '#ffd700',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Inter", sans-serif',
    layout: 'split',
  },
  {
    id: 'paris-metro',
    name: 'Paris Métro',
    background: 'linear-gradient(135deg, #2c3e50 0%, #3498db 100%)',
    backgroundImage: 'repeating-linear-gradient(90deg, transparent, transparent 50px, rgba(255,255,255,0.03) 50px, rgba(255,255,255,0.03) 51px)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.9)',
    accentColor: '#27ae60',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Helvetica Neue", sans-serif',
    layout: 'split',
  },
  {
    id: 'amsterdam-tram',
    name: 'Amsterdam Tram',
    background: 'linear-gradient(135deg, #ff6b6b 0%, #ee5a6f 50%, #c44569 100%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.9)',
    accentColor: '#ffd93d',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Inter", sans-serif',
    layout: 'split',
  },
  {
    id: 'zürich-tram',
    name: 'Zürich Tram',
    background: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.85)',
    accentColor: '#00adb5',
    style: 'minimal',
    clockStyle: 'digital',
    fontFamily: '"Helvetica", sans-serif',
    layout: 'split',
  },
  {
    id: 'copenhagen-blue',
    name: 'Copenhagen Blue',
    background: 'linear-gradient(135deg, #1e3a8a 0%, #3b82f6 50%, #60a5fa 100%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.9)',
    accentColor: '#fbbf24',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Inter", sans-serif',
    layout: 'split',
  },
  {
    id: 'vienna-modern',
    name: 'Vienna Modern',
    background: 'linear-gradient(135deg, #434343 0%, #000000 100%)',
    backgroundImage: 'radial-gradient(circle at 80% 20%, rgba(220,38,38,0.15) 0%, transparent 50%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.8)',
    accentColor: '#dc2626',
    style: 'minimal',
    clockStyle: 'digital',
    fontFamily: '"Inter", sans-serif',
    layout: 'split',
  },
  {
    id: 'barcelona-metro',
    name: 'Barcelona Metro',
    background: 'linear-gradient(135deg, #fc4a1a 0%, #f7b733 100%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.9)',
    accentColor: '#ffffff',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Roboto", sans-serif',
    layout: 'split',
  },
  {
    id: 'prague-night',
    name: 'Prague Night',
    background: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.85)',
    accentColor: '#8b5cf6',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Inter", sans-serif',
    layout: 'split',
  },
];
