import { Theme } from './types';

export const vibrantGradientThemes: Theme[] = [
  {
    id: 'sunset-vibes',
    name: 'Sunset Vibes',
    background: 'linear-gradient(135deg, #ff9a56 0%, #ff6b95 50%, #c471f5 100%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.9)',
    accentColor: '#ffd700',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Inter", sans-serif',
    layout: 'centered',
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    background: 'linear-gradient(135deg, #2193b0 0%, #6dd5ed 100%)',
    backgroundImage: 'radial-gradient(circle at 20% 80%, rgba(255,255,255,0.1) 0%, transparent 50%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.9)',
    accentColor: '#ffffff',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Inter", sans-serif',
    layout: 'split',
  },
  {
    id: 'purple-haze',
    name: 'Purple Haze',
    background: 'linear-gradient(135deg, #6a3093 0%, #a044ff 100%)',
    backgroundImage: 'radial-gradient(circle at 50% 50%, rgba(255,255,255,0.05) 0%, transparent 60%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.9)',
    accentColor: '#ffd93d',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Inter", sans-serif',
    layout: 'centered',
  },
  {
    id: 'mint-fresh',
    name: 'Mint Fresh',
    background: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.9)',
    accentColor: '#ffffff',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Inter", sans-serif',
    layout: 'centered',
  },
  {
    id: 'coral-reef',
    name: 'Coral Reef',
    background: 'linear-gradient(135deg, #ff6e7f 0%, #bfe9ff 100%)',
    backgroundImage: 'radial-gradient(circle at 30% 40%, rgba(255,255,255,0.2) 0%, transparent 50%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.95)',
    accentColor: '#ff6e7f',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Inter", sans-serif',
    layout: 'split',
  },
  {
    id: 'neon-nights',
    name: 'Neon Nights',
    background: 'linear-gradient(135deg, #08203e 0%, #557c93 100%)',
    backgroundImage: 'radial-gradient(circle at 80% 20%, rgba(255,0,255,0.2) 0%, transparent 40%), radial-gradient(circle at 20% 80%, rgba(0,255,255,0.2) 0%, transparent 40%)',
    timeColor: '#00ffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.85)',
    accentColor: '#ff00ff',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Orbitron", sans-serif',
    layout: 'split',
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    background: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 50%, #ff9a9e 100%)',
    timeColor: '#5a3f37',
    textColor: '#5a3f37',
    textSecondary: 'rgba(90, 63, 55, 0.8)',
    accentColor: '#d55d92',
    style: 'modern',
    clockStyle: 'analog-minimal',
    fontFamily: '"Inter", sans-serif',
    layout: 'centered',
  },
  {
    id: 'emerald-city',
    name: 'Emerald City',
    background: 'linear-gradient(135deg, #0f9b0f 0%, #000000 100%)',
    backgroundImage: 'radial-gradient(circle at 30% 30%, rgba(15,155,15,0.3) 0%, transparent 60%)',
    timeColor: '#00ff00',
    textColor: '#00ff00',
    textSecondary: 'rgba(0, 255, 0, 0.8)',
    accentColor: '#00ff00',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Share Tech Mono", monospace',
    layout: 'split',
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    background: 'linear-gradient(135deg, #f12711 0%, #f5af19 100%)',
    timeColor: '#ffffff',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.95)',
    accentColor: '#ffffff',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Inter", sans-serif',
    layout: 'centered',
  },
  {
    id: 'arctic-aurora',
    name: 'Arctic Aurora',
    background: 'linear-gradient(135deg, #0c1445 0%, #1a2456 50%, #2a3f66 100%)',
    backgroundImage: 'radial-gradient(ellipse at 50% 0%, rgba(138,255,203,0.2) 0%, transparent 50%), radial-gradient(ellipse at 0% 100%, rgba(138,176,255,0.2) 0%, transparent 50%)',
    timeColor: '#8affcb',
    textColor: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.85)',
    accentColor: '#8ab0ff',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Inter", sans-serif',
    layout: 'split',
  },
  {
    id: 'cyberpunk-red',
    name: 'Cyberpunk Red',
    background: 'linear-gradient(135deg, #000000 0%, #1a0000 50%, #330000 100%)',
    backgroundImage: 'repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(255,0,0,0.03) 2px, rgba(255,0,0,0.03) 4px)',
    timeColor: '#ff003c',
    textColor: '#ff003c',
    textSecondary: 'rgba(255, 0, 60, 0.8)',
    accentColor: '#00ffff',
    style: 'modern',
    clockStyle: 'digital',
    fontFamily: '"Orbitron", sans-serif',
    layout: 'split',
  },
  {
    id: 'lavender-dreams',
    name: 'Lavender Dreams',
    background: 'linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)',
    timeColor: '#4a4a8a',
    textColor: '#4a4a8a',
    textSecondary: 'rgba(74, 74, 138, 0.8)',
    accentColor: '#8b5cf6',
    style: 'modern',
    clockStyle: 'analog-bauhaus',
    fontFamily: '"Inter", sans-serif',
    layout: 'centered',
  },
];
